numpy = numerical + python

In [97]:
# Installing Any new package

!pip install numpy

### Load in NumPy (remember to pip install numpy first)

In [98]:
import numpy as np

### How Array differs from  list

1. Array will have only single data types
2. Memory efficient & computational efficient
3. Multiple dimensional data 

### The Basics

In [233]:
# Define Array

a = np.array([1,2,3], dtype='int32')

print(a)

[1 2 3]


In [235]:
a.shape

(3,)

In [236]:
b = np.array([[9.0,8.0,7.0],
              [6.0,5.0,4.0]])

print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [237]:
# Get Dimension
# Number of array dimensions

a.ndim

1

In [112]:
# Get Shape

a.shape

b.shape

(2, 3)

In [114]:
# Get Type
a.dtype

b.dtype

dtype('float64')

In [121]:
a.dtype

dtype('int32')

In [122]:
# Get Length of one array element in bytes.
a.itemsize

4

In [117]:
x = np.array([1,2,3], dtype = np.float64)

x.itemsize

8

In [119]:
x = np.array([1,2,3], dtype = np.complex128)

x.itemsize

16

In [123]:
# Get total size
a.nbytes

12

In [126]:
np.prod(a.shape) * a.itemsize

12

In [18]:
x = np.zeros((3,5,2), dtype=np.complex128)

x.nbytes

480

In [17]:
np.prod(x.shape) * x.itemsize

24

In [35]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [127]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [130]:
# Get a specific element [r, c]

a[1, 5]

13

In [131]:
# Get a specific row 

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [134]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [141]:
# Getting a little more fancy [startindex:endindex:stepsize]

a[0, 1:-1:3]

array([2, 5])

In [142]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [143]:
a[1,5] = 20

In [144]:
a[:,2]

array([ 3, 10])

In [147]:
# Changing values in 3rd column
a[:,2] = [1,2]

print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


* 3-d example

In [150]:
a = np.array([[1,2,3],[3,4,5]])

In [166]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [167]:
b.ndim

3

In [168]:
b.shape

(2, 2, 2)

In [171]:
# Get specific element (work outside in)

b[0,1,1]

4

In [172]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [173]:
# replace 

b[:,1,:] = [[9,9],[8,8]]

In [174]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [181]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [184]:
# All 0s matrix

np.zeros((2,3), dtype = 'int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [195]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [188]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [191]:
# Any other number

np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [202]:
a = np.array([[1,3],[3,5]])

In [203]:
a.shape

(2, 2)

In [204]:
# Any other number (full_like) With other array  as reference

np.full_like(a, 4)

array([[4, 4],
       [4, 4]])

In [208]:
# Random decimal numbers

np.random.rand(4,2)

array([[0.63099132, 0.92950385],
       [0.88475171, 0.9357503 ],
       [0.6725353 , 0.29255044],
       [0.46819495, 0.54271224]])

In [214]:
# Random Integer values 

# 10 is exclusive

np.random.randint(6,10, size=(3,3))

array([[7, 6, 7],
       [6, 9, 7],
       [7, 8, 9]])

In [218]:
# The identity matrix - One in the diagonal of the matrix, rows & column will be same

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [335]:
# Repeat an array

arr = np.array([[1,2,3]])

r1 = np.repeat(arr,3, axis = 1) # axis= 0 -> column level , axis =1 -> row level

print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [229]:
output = np.ones((5,5))

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [230]:
z = np.zeros((3,3))

z[1,1] = 9

print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [232]:
output[1:-1,1:-1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
output[1:-1,1:-1] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

### Shallow copy & deep copy

* shallow copy creates a reference to the parent but not the actual copy
* deep copy it actually creates the new object with  new id

In [241]:
a = np.array([1,2,3])

In [242]:
b = a

In [248]:
a[2] = 99

In [251]:
a

array([ 1,  2, 99])

In [250]:
b

array([ 1,  2, 99])

In [245]:
id(a)

2112037701552

In [246]:
id(b)

2112037701552

In [252]:
a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [254]:
a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


### Broadcasting  

*  It allows to do same computation across all the elements of the array in the vectorised format

In [260]:
a + 2

array([3, 4, 5, 6])

In [261]:
a - 2

array([-1,  0,  1,  2])

In [262]:
a * 2

array([2, 4, 6, 8])

In [263]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [269]:
a = np.array([1,2,3,4])

b = np.array([5,6,7,8,9])

In [270]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [271]:
b = np.array([1,0,1,0])

a + b

array([2, 2, 4, 4])

In [272]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [275]:
# Take the sin

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [308]:
a = np.ones((3,3))

print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [309]:
b = np.full((3,3), 2)

print(b)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [310]:
np.matmul(a,b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [312]:
a * b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [313]:
# Find the determinant
c = np.identity(3)

np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [338]:
stats = np.array([[1,2,3],[4,9,6]])

stats

array([[1, 2, 3],
       [4, 9, 6]])

In [317]:
np.min(stats)

1

In [319]:
np.max(stats, axis=1) # computational  method

array([3, 6])

In [321]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [329]:
np.max(stats)

6

In [341]:
np.argmax(stats, axis = 1)

array([2, 1], dtype=int64)

In [343]:
np.argmax(stats, axis = 0)

array([1, 1, 1], dtype=int64)

In [353]:
stats = np.array([[1,2,3],[4,9,6]])

stats

array([[1, 2, 3],
       [4, 9, 6]])

In [356]:

stats[np.where(stats > 5)]

array([9, 6])

In [352]:
np.argwhere(stats > 5)

# [(row, position),(row, position)] -> two elements

array([[1, 1],
       [1, 2]], dtype=int64)

### Reorganizing Arrays

In [373]:
Array1 = np.array([[1,2,3,4],[5,6,7,8]])

print(Array1)

[[1 2 3 4]
 [5 6 7 8]]


In [387]:
Array2 = Array1.reshape((2,2,2))

print(Array2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [405]:
# (-1) this convert that array into 1-dimension

a.reshape(-1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [406]:
# this func will converts all arrays into 1 dimensional array

a.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [367]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])

v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))

h2 = np.zeros((2,2))

In [370]:
h2

array([[0., 0.],
       [0., 0.]])

In [369]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [368]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [390]:
filedata = np.genfromtxt('data.txt', delimiter=',')

filedata = filedata.astype('int32')

print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [393]:
(((filedata > 50) & (filedata < 100)))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [396]:
~(((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [398]:
# ~ will be used to inverse the condition

filedata[~(((filedata > 50) & (filedata < 100)))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1])

In [399]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])